### ISSUE TITLE
Java 9 - NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by pditommaso** [jexler/grengine#5]
When using Grengine 1.2.0 with Java 9 I'm getting the following exception:

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at ch.grengine.source.SourceUtil.hash(SourceUtil.java:345)
	at ch.grengine.source.SourceUtil.md5(SourceUtil.java:362)
	at ch.grengine.source.DefaultTextSource.<init>(DefaultTextSource.java:84)
	at ch.grengine.source.DefaultSourceFactory.fromText(DefaultSourceFactory.java:106)
	at ch.grengine.BaseGrengine.load(BaseGrengine.java:389)
	at ch.grengine.BaseGrengine$load.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at nextflow.config.ComposedConfigSlurper.loadScript(ComposedConfigSlurper.groovy:178)
	at nextflow.config.ComposedConfigSlurper.parse(ComposedConfigSlurper.groovy:229)
	at nextflow.config.ComposedConfigSlurper$parse.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:242)
	at nextflow.config.ConfigBuilder$buildConfig0$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at nextflow.config.ConfigBuilder.buildConfig(ConfigBuilder.groovy:234)
	at nextflow.config.ConfigBuilder$buildConfig$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:490)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:203)
	at nextflow.cli.Launcher.run(Launcher.groovy:410)
	at nextflow.cli.Launcher.main(Launcher.groovy:564)

```

As far as I know the package `javax.xml.bind` has been removed by default.

**Comment by jexler** [comment]
Thanks, I intend to fix/release this until Monday at the latest, and strange that the Gradle build with unit tests had worked without any issues on a recent JDK 9 Early Access version...

**Comment by jexler** [comment]
Commit "eliminated dependency on javax.xml.bind.DatatypeConverter":
https://github.com/jexler/grengine/commit/659f4fe8a5433339bb6ac591d79a687374687dc7

**Comment by jexler** [comment]
I could reproduce the issue with jdk9-ea+167 (using gradle 3.5 plus `export JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'`, c.f. https://github.com/gradle/gradle/issues/1095). With the fix https://github.com/jexler/grengine/commit/659f4fe8a5433339bb6ac591d79a687374687dc7 the build plus unit tests pass. So, ready to make a Grengine release this weekend.

**Comment by jexler** [comment]
Release is out, 'ch.grengine:grengine:1.2.1' can be pulled from mvn central.

**Comment by jexler** [comment]
**Release Notes**

1.2.1 (28 Apr 2017)
* Fix: Java 9 compatibility (removed dependency on javax.xml.bind package, which is not available by default on Java 9).

**Comment by pditommaso** [comment]
👍
